// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLz8-k5znxFsIstKFD3ycV9wMUDC-splM',
    appId: '1:257026834758:web:5016b6e5c6c1c3bcb0e547',
    messagingSenderId: '257026834758',
    projectId: 'fir-chat-app-d7654',
    authDomain: 'fir-chat-app-d7654.firebaseapp.com',
    storageBucket: 'fir-chat-app-d7654.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxhu2Gj8TLAcvmDdWJdIqbqSX1m2BXDs',
    appId: '1:257026834758:android:085daecd20e06c0cb0e547',
    messagingSenderId: '257026834758',
    projectId: 'fir-chat-app-d7654',
    storageBucket: 'fir-chat-app-d7654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2yExvIczPXj6FvtM9GBUuIYyKM4kl3IA',
    appId: '1:257026834758:ios:8ddcbbb0df2406aab0e547',
    messagingSenderId: '257026834758',
    projectId: 'fir-chat-app-d7654',
    storageBucket: 'fir-chat-app-d7654.appspot.com',
    iosClientId: '257026834758-fkk7ut90rngrjk7autfp34f6hiufqlv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2yExvIczPXj6FvtM9GBUuIYyKM4kl3IA',
    appId: '1:257026834758:ios:8ddcbbb0df2406aab0e547',
    messagingSenderId: '257026834758',
    projectId: 'fir-chat-app-d7654',
    storageBucket: 'fir-chat-app-d7654.appspot.com',
    iosClientId: '257026834758-fkk7ut90rngrjk7autfp34f6hiufqlv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
